src/Project/Sugcon/SugconAnzSxa/src/Layout.tsx
src/Project/Sugcon/SugconAnzSxa/src/assets/app.css.old
src/Project/Sugcon/SugconAnzSxa/src/assets/app.scss
src/Project/Sugcon/SugconAnzSxa/src/assets/components/organiserList.scss
src/Project/Sugcon/SugconAnzSxa/src/assets/components/sponsorList.scss
src/Project/Sugcon/SugconAnzSxa/src/components/Sugon/OrganiserList.tsx
src/Project/Sugcon/SugconAnzSxa/src/components/Sugon/SponsorList.tsx

Styled OrganiserList and SponsorList plus some basics.

Styling organiser list

---

src/Project/Sugcon/SugconAnzSxa/src/assets/app.scss
src/Project/Sugcon/SugconAnzSxa/src/assets/components/navigation.scss
src/Project/Sugcon/SugconAnzSxa/src/assets/components/sponsorList.scss
src/Project/Sugcon/SugconAnzSxa/src/components/SXA/Title.tsx
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Home/Organisation.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Home/Sponsors.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Home/Test.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Home/Test/Test Sponsors.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Presentation/Partial Designs/SugconAnzFooter.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Presentation/Partial Designs/SugconAnzHeader.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Presentation/Partial Designs/SugconAnzHeader/Data/Text 1.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Presentation/Styles/Navigation.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Presentation/Styles/Navigation/Main Navigation.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Presentation/Styles/Navigation/Mobile Navigation.yml
src/Project/Sugcon/items/templatesFeature/Sugcon/Sugcon Base Components/Sponsor/Data/SponsorName.yml

Styled the Header, Footer and Title. Still some open topics: 
- Header bar with links to other sugcon resources does not have fullwidth background
- footer social links component is missing
- mobile navigation is missing

Styling title header

---

src/Project/Sugcon/SugconAnzSxa/src/assets/app.scss
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Presentation/Partial Designs/SugconAnzHeader.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Presentation/Styles/Container Background Styles/Background Dark Grey.yml

Fixed Header Styling (grey bar)

fixed header layout

---

.gitignore
xmcloud.build.json

Incorporating changes from Andy/Sebastian that got his local deployment to work (except for the changes to the SLN file)

XM Cloud build - Attempting to fix build

---

src/Project/Sugcon/SugconAnzSxa/src/components/Sugon/Agenda.tsx
src/Project/Sugcon/SugconAnzSxa/src/components/Sugon/Session.tsx
src/Project/Sugcon/SugconAnzSxa/src/components/Sugon/Speaker.tsx
src/Project/Sugcon/SugconAnzSxa/src/lib/sessionize/fetch-sessonize-data.ts
src/Project/Sugcon/SugconAnzSxa/src/lib/sessionize/sessionizeData.ts
src/Project/Sugcon/items/components/Sugcon/Sugcon Base Components/Agenda.yml
src/Project/Sugcon/items/components/Sugcon/Sugcon Base Components/Session.yml
src/Project/Sugcon/items/components/Sugcon/Sugcon Base Components/Speaker.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Data/Agenda.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Data/Agenda/Agenda.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Data/Session.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Data/Session/Session.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Data/Speaker.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Data/Speaker/Speaker.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Home/Agenda.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Home/Sessions.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Home/Speakers.yml
src/Project/Sugcon/items/templatesFeature/Sugcon/Sugcon Base Components/Agenda/Data.yml
src/Project/Sugcon/items/templatesFeature/Sugcon/Sugcon Base Components/Agenda/Data/SessionizeURL.yml
src/Project/Sugcon/items/templatesFeature/Sugcon/Sugcon Base Components/Agenda/Data/Title.yml
src/Project/Sugcon/items/templatesFeature/Sugcon/Sugcon Base Components/Session/Data/SessionizeURL.yml
src/Project/Sugcon/items/templatesFeature/Sugcon/Sugcon Base Components/Session/Data/Title.yml
src/Project/Sugcon/items/templatesFeature/Sugcon/Sugcon Base Components/Speaker/Data/SessionizeURL.yml
src/Project/Sugcon/items/templatesFeature/Sugcon/Sugcon Base Components/Speaker/Data/Title.yml

This pull request contains changes Sugcon ANZ only, to make Sessionize pages (Agenda, Speakers, Sessions) to use component level getStaticProps so they are statically generated pages. The page data of title and the Sessionize API URL has also been moved inside of XM.

Sessionize

---

src/Project/MvpSite/rendering/Program.cs
src/Project/MvpSite/rendering/Startup.cs

Migrated to dotnet 6 minimal hosting model
Closes #15

Changed to dotnet6 minimal hosting model

---

src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Presentation/Partial Designs/SugconAnzHeader/Data/Image 1.yml

A change to the SUGCON logo in the header partial design to always link to the home page.

Header link

---

src/Project/MvpSite/rendering/Controllers/DefaultController.cs
src/Project/MvpSite/rendering/Views/Default/Index.cshtml
src/Project/MvpSite/rendering/Views/Shared/Error.cshtml
src/Project/MvpSite/rendering/Views/Shared/NotFound.cshtml
src/Project/MvpSite/rendering/Views/Shared/_ErrorLayout.cshtml
src/Project/MvpSite/rendering/Views/_ViewStart.cshtml
src/Project/MvpSite/rendering/wwwroot/sass/layout/footer.scss
src/Project/MvpSite/rendering/wwwroot/sass/layout/layout.scss
src/Project/MvpSite/rendering/wwwroot/style/main.css

Created styled 404 & 500 pages for MVP site.
Closes #97

Setup 404 and 500 pages for MVP site.

---

.github/workflows/deploy_XM_Cloud.yml

Re-introduced automated publishing for XM Cloud deploys.

Re-Introduced Automated XM Cloud Publishing

---

src/Project/Sugcon/SugconAnzSxa/src/components/Sugon/SponsorList.tsx
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Data/Sponsors/Aceik.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Data/Sponsors/Dataweavers.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Data/Sponsors/Deloitte Digital.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Data/Sponsors/Espire Infolabs.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Data/Sponsors/Just After Midnight.yml
src/Project/Sugcon/items/templatesFeature/Sugcon/Sugcon Base Components/Sponsor/Data/SponsorDescription.yml

Description field has been added to the template, initial data population, and also some markup updates to the component to support the description field.

Sponsor add description

---

src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Data/Sponsors/Aceik.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Data/Sponsors/Dataweavers.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Data/Sponsors/Deloitte Digital.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Data/Sponsors/Espire Infolabs.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Data/Sponsors/Just After Midnight.yml

All Rich Text fields have been edited to remove inline styling like color, background color, etc.

ANZ Sponsors - Removed inline styling

---

src/Project/Sugcon/SugconAnzSxa/src/components/Sugcon/SponsorList.tsx

Updated from Text to RichText to render markup properly.

ANZ Sponsors - Fixing JSS control type used for Sponsor description

---

.env.template
docker-compose.edge.yml
docker-compose.override.yml
init.ps1
src/Project/Sugcon/SugconAnzSxa/package-lock.json
src/Project/Sugcon/SugconAnzSxa/package.json
src/Project/Sugcon/SugconAnzSxa/sitecore/config/sugcon-anz.config
src/Project/Sugcon/SugconAnzSxa/src/pages/api/editing/render.ts
src/Project/Sugcon/SugconEuSxa/package-lock.json
src/Project/Sugcon/SugconEuSxa/package.json
src/Project/Sugcon/SugconEuSxa/sitecore/config/sugcon-eu-sxa.config
src/Project/Sugcon/SugconEuSxa/src/pages/api/editing/render.ts
src/Project/Sugcon/SugconEuSxa/src/pages/api/healthz.ts
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Settings.yml
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Settings/Site Grouping/SugconAnzSxa.yml
src/Project/Sugcon/items/content/Sugcon/SugconEuSxa/Settings.yml
src/Project/Sugcon/items/content/Sugcon/SugconEuSxa/Settings/Site Grouping/SugconEuSxa.yml
src/Project/Sugcon/items/content/Sugcon/SugconShared/Settings.yml
xmcloud.build.json

- Fixed issue with multiple rendering hosts not supporting hyphens in name
- Added Healthz page to SUGCON EU head.

Changes to enable Experience Editor & Pages for SUGCON EU

---

docker-compose.override.yml
src/Foundation/Configuration/rendering/AppSettings/MvpSiteSettings.cs
src/Project/MvpSite/rendering/Startup.cs

Fixes to get the Experience Editor working for the MVP site when running in Full Local Development mode
Closes #116

Mvp Local Experience Editor Fixes

---

src/Project/Sugcon/SugconAnzSxa/src/Layout.tsx
src/Project/Sugcon/SugconEuSxa/src/Layout.tsx
src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Home.yml
src/Project/Sugcon/items/content/Sugcon/SugconEuSxa/Home.yml
src/Project/Sugcon/items/content/Sugcon/SugconEuSxa/Home/Data/Text 1.yml

Updated page titles for both SUGCON sites
Corrected issue with SUGCON EU Homepage renderings

SUGCON Site Changes

---

Packages.props
src/Feature/Selections/rendering/Models/Apply/ApplicationFormModel.cs
src/Feature/Selections/rendering/ViewComponents/Apply/ApplicationFormViewComponent.cs
src/Feature/Selections/rendering/ViewComponents/DashboardViewComponent.cs
src/Feature/Selections/rendering/Views/Shared/Components/ApplyApplicationForm/Default.cshtml
src/Feature/Selections/rendering/Views/Shared/Components/SelectionsDashboard/Default.cshtml

+ Users without country set now get an error with some detail when trying to start application
+ Updated API Client to v3.1.1 to utilize new Domain
+ Dashboard no longer empty when there's no current selection
+ Name appears on dashboard (easier user identification)

fix: Adjustments for new users without Country

---

.github/workflows/CI-CD_MVP.yml
.github/workflows/CI-CD_SUGCON_ANZ.yml
.github/workflows/CI-CD_SUGCON_EU.yml
.github/workflows/CI-CD_XM_Cloud.yml
.github/workflows/deploy_xmCloud.yml

- Added Workflow Dispatch event support to all CI-CD pipelines, enabling ability to manually trigger a workflow
- Inverted commit path monitoring logic for XM-Cloud workflow to remove unnecessary builds that were happening
- Fixed hardcoded label on XM Cloud deployments

Tidied the GitHub Actions definitions

---

src/Project/MvpSite/rendering/wwwroot/robots.txt

* Setup MVP site robots.txt to allow crawlers to index site
* Disallowed indexing of application related pages.
Closes #35

Updated MVP robots.txt

---

src/Project/MvpSite/rendering/Views/Shared/_Layout.cshtml

Fixed null checking that was stopping the MVP 404 page from rendering

Improved null checking on layout stopping 404 page from rendering

---

src/Project/MvpSite/rendering/Controllers/DefaultController.cs
src/Project/MvpSite/rendering/Models/ErrorViewModel.cs
src/Project/MvpSite/rendering/Views/Shared/Error.cshtml
src/Project/MvpSite/rendering/Views/Shared/NotFound.cshtml

Fixed the model issue with the error pages so they can now render correctly.

Fixed the error pages to leverage the new LayoutPageModel

---

src/Feature/Selections/rendering/Configuration/MvpSelectionsOptions.cs
src/Feature/Selections/rendering/Extensions/DependencyInjectionExtensions.cs
src/Feature/Selections/rendering/ViewComponents/Apply/ApplicationFormViewComponent.cs

Contribution Time Frame Validation

---

src/Feature/SeoSocialTags/SeoSocialTags.module.json
src/Feature/SeoSocialTags/items/templates/Social and SEO Tagging.yml
src/Feature/SeoSocialTags/items/templates/Social and SEO Tagging/_MetaTags.yml
src/Feature/SeoSocialTags/items/templates/Social and SEO Tagging/_MetaTags/Meta Tags.yml
src/Feature/SeoSocialTags/items/templates/Social and SEO Tagging/_MetaTags/Meta Tags/MetaDescription.yml
src/Feature/SeoSocialTags/items/templates/Social and SEO Tagging/_MetaTags/Meta Tags/MetaKeywords.yml
src/Feature/SeoSocialTags/items/templates/Social and SEO Tagging/_OpenGraphTags.yml
src/Feature/SeoSocialTags/items/templates/Social and SEO Tagging/_OpenGraphTags/Open Graph Tags.yml
src/Feature/SeoSocialTags/items/templates/Social and SEO Tagging/_OpenGraphTags/Open Graph Tags/OgDescription.yml
src/Feature/SeoSocialTags/items/templates/Social and SEO Tagging/_OpenGraphTags/Open Graph Tags/OgImage.yml
src/Feature/SeoSocialTags/items/templates/Social and SEO Tagging/_OpenGraphTags/Open Graph Tags/OgTitle.yml
src/Feature/SeoSocialTags/items/templates/Social and SEO Tagging/_OpenGraphTags/Open Graph Tags/OgType.yml
src/Project/MvpSite/items/content/MvpSite/Home/404.yml
src/Project/MvpSite/items/content/MvpSite/Home/Application.yml
src/Project/MvpSite/items/content/MvpSite/Home/Application/Apply.yml
src/Project/MvpSite/items/content/MvpSite/Home/Application/My-Data.yml
src/Project/MvpSite/items/content/MvpSite/Home/Directory.yml
src/Project/MvpSite/items/content/MvpSite/Home/Mentor-Program.yml
src/Project/MvpSite/items/content/MvpSite/Home/Podcast.yml
src/Project/MvpSite/items/content/MvpSite/Home/Thank-you.yml
src/Project/MvpSite/items/content/MvpSite/Shared Content/Selections/Any/My Data Edit.yml

fixed missing parent. removed non serialized item MvpSite and moved Social and SEO Tagging item to Feature folder

fixed missing parent.

---

.github/issue_template/feature_request.md
.github/issue_template/issue_report.md
.github/pull_request_template.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

A series of documentation updates that need to happen now we're live.
- Defined CoC
- Defined Contributing Guide
- Defined Issue & Feature templates
- Updated README
Closes #21

Post Launch Repository Housekeeping

---

docker-compose.override.yml
src/Project/MvpSite/items/content/MvpSite/Home/Application/My-Data.yml

Fixed issue for MVP site running locally
Added missing profiles rendering on MVP selections.

Fixed EE issue for MVP site locally, updated profiles renderings

---

.github/workflows/CI-CD_SUGCON_ANZ.yml
.github/workflows/CI-CD_SUGCON_EU.yml
XmCloud.sln
xmcloud.build.json

- Ensure deploys are built against correct environment
- Adds temp workaround to allow deploy app builds to progress again.
- 
Closes #133 
Closes #144

Changed build target SUGCON site builds, re-introduced sln file to workaround deploy app issue

---

src/Project/Sugcon/SugconEuSxa/src/assets/components/sponsorList.scss

Fixed styling issue with sponsors logos

---

src/Project/MvpSite/rendering/Controllers/DefaultController.cs

Added redirect for secure pages when user is unauthenticated

---

Packages.props
src/Feature/User/rendering/Extensions/StartUpExtensions.cs
src/Feature/User/rendering/Helpers/RefreshTokenHelper.cs
src/Project/MvpSite/rendering/Startup.cs
src/XmCloudIntroduction.sln.DotSettings

Adds behavior to validate token lifetime and utilize refresh token to refresh underlying tokens.
Currently people are getting errors about token validity from the API due to the tokens in the website session not being refreshed.
Fixes #174
Locally tested
Local environment with the preview Okta
No effects on anything besides Authentication/Authorization

Added Refresh Token logic for authentication

---

src/Feature/People/rendering/Constants.cs
src/Feature/People/rendering/PeopleFinder/MvpFinder.cs

Fixed a typo in a LINQ Where clause
Causes a Nullref exception which makes the Directory fail to load
Fixes #197 
Local environment
Affects no other code

Fixed Nullref due to binary operator

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
src/Feature/People/rendering/Constants.cs

This commit reverts the previous workaround for the issue with Experience Edge

Remove edge workaround

---

.github/workflows/CI-CD_SUGCON_ANZ.yml
.github/workflows/CI-CD_SUGCON_EU.yml
.github/workflows/build_NextJs.yml
src/Project/Sugcon/SugconAnzSxa/src/pages/404.tsx
src/Project/Sugcon/SugconAnzSxa/src/pages/[[...path]].tsx
src/Project/Sugcon/SugconEuSxa/src/pages/404.tsx
src/Project/Sugcon/SugconEuSxa/src/pages/[[...path]].tsx

Update to SSG sites CI/CD to not generate static pages.
- [x New feature (non-breaking change which adds functionality)

Restructured SSG CI Builds

---

src/Project/Sugcon/SugconEuSxa/src/assets/components/hero.scss
src/Project/Sugcon/SugconEuSxa/src/components/Sugcon/Hero.tsx
src/Project/Sugcon/items/templatesFeature/Sugcon/Sugcon Base Components/Hero/Data/Description.yml

Extend Hero component with a description field to add proper content
Teste on my local, only on EU website. Can be added later for the other websites.
On Desktop:
On Mobile:

Extend Hero component with a description field

---

.github/workflows/CI-CD_SUGCON_Events.yml

Creates CI/CD pipeline for SUGCON events site, automating deployments on code changes
Closes #209

Create CI/CD pipeline for SUGCON Events site

---

.github/workflows/CI-CD_SUGCON_Events.yml
README.md

Fixes for the SUGCON Events CI/CD pipeline

Fixes for the SUGCON Events CI/CD pipeline

---

src/Project/Sugcon/SugconEuSxa/src/components/Sugcon/Hero.tsx

Fixing issue with Link field added to Hero causing Vercel build errors

Added display logic wrapping link field for hero

---

src/Feature/Selections/rendering/ViewComponents/Admin/ScoreCardsViewComponent.cs

Fixed loading Titles on ScoreCards
Local + Staging API

Fixed Titles incorrectly loading

---

src/Project/Sugcon/SugconEuSxa/src/assets/components/sponsorList.scss
src/Project/Sugcon/SugconEuSxa/src/components/Sugcon/SponsorList.tsx
src/Project/Sugcon/items/content/Sugcon/SugconEuSxa/Presentation/Headless Variants/SponsorList/GoldSilver.yml
src/Project/Sugcon/items/content/Sugcon/SugconEuSxa/Presentation/Headless Variants/SponsorList/Secondary.yml
src/Project/Sugcon/items/content/Sugcon/SugconEuSxa/Presentation/Styles/Container Background Styles/Padding Bottom 5.yml

- Text descriptions was missing on Platinum sponsors
- Add a new variant Secondary in in order to support links and text description only for a set of sponsors
- A cleanup of the scss files was needed
On my local, see the screenshot of the end result.

Website sponsors changes

---

src/Project/Sugcon/SugconEuSxa/src/Layout.tsx
src/Project/Sugcon/items/templatesFeature/Sugcon/Social and SEO Tagging/_MetaTags/Meta Tags/MetaCustomAttributes.yml

Be able to add custom metadata to the website 
Main reason si to be able to validate the website for Google Search Console https://search.google.com/search-console?
On my local

Website custom metadata

---

.config/dotnet-tools.json
.env.template
sitecore.json

Bumped the version of the Docker base images, Sitecore CLI version, and Sitecore CLI package versions.
Closes #242

Bumped docker base image versions, and sitecore CLI & package versions

---

src/Feature/Selections/rendering/ViewComponents/Admin/ScoreCardsViewComponent.cs

Fixed a bug where Admin Score cards would display an Applicant as not awarded because the Title wasn't loaded in the first 100 results
Award button would be available instead of Remove Award button
Local environment against Staging API

Fixed Admin Score Cards

---

.github/workflows/CI-CD_MVP.yml

Added condition to allow manual run to execute deployment steps

Update CI-CD Actions

---

Packages.props
src/Project/MvpSite/rendering/Mvp.Project.MvpSite.Rendering.csproj
src/Project/MvpSite/rendering/Startup.cs

Setting up AppInsights connection for the MVP Rendering host.
The package & code is referenced, the connectionstring will be populated by an Env var in the AzureWebApp.
Closes #248

Setting up app insights connection for the MVP rendering host

---

.env.template
README.md
docker-compose.edge.yml
docker-compose.override.yml
docker-compose.yml
up.ps1

* Updated docker-compose yaml files to `v2` format.
* Updated ps1 script to force `v2` method of executing containers
* Tidied up Environment value warnings
* Updated README
Closes #252

Migration repository to Docker Compose v2

---

sitecore.json

Update Sitecore.DevEx.Extensibility.XMCloud cli plugin to latest version.

Update xmcloud cli plugin

---

.github/workflows/CI-CD_SUGCON_India.yml

Setup CI/CD for SUGCON India site

Created CI/CD script for SUGCON India site

---

src/Project/Sugcon/SugconEuSxa/src/Layout.tsx
src/Project/Sugcon/SugconIndiaSxa/src/Layout.tsx

Fixed issue with SUGCON site Html titles being incorrect

---

src/Project/Sugcon/SugconHomeStatic/index.html
src/Project/Sugcon/SugconIndiaSxa/src/assets/components/organiserList.scss
src/Project/Sugcon/SugconIndiaSxa/src/components/Sugcon/OrganiserList.tsx
src/Project/Sugcon/items/content/Sugcon/SugconIndiaSxa/Data/Organisers/Hardeep Bhamra.yml
up.ps1

Changes to SUGCON india organiser page, updated India site link on main .events site

Changes to SUGCON India site

---

docker-compose.edge.yml
up.ps1

Ensured that SUGCON India site is also created when working in Edge mode with Docker.
Closes #263

Added SUGCON India to Edge mode with Docker scripts

---

init.ps1
nuget.config

Updated to move repository to run from new Sitecore feed and away from MyGet.

Updated to use new Nuget feed

---

src/Project/Sugcon/SugconNaSxa/package-lock.json
src/Project/Sugcon/SugconNaSxa/package.json
src/Project/Sugcon/SugconNaSxa/scripts/config/plugins/multisite.ts
src/Project/Sugcon/SugconNaSxa/src/Navigation.tsx
src/Project/Sugcon/SugconNaSxa/src/components/CdpPageView.tsx
src/Project/Sugcon/SugconNaSxa/src/lib/page-props-factory/plugins/component-props.ts
src/Project/Sugcon/SugconNaSxa/src/lib/page-props-factory/plugins/preview-mode.ts
src/Project/Sugcon/SugconNaSxa/src/lib/page-props.ts
src/Project/Sugcon/SugconNaSxa/src/lib/site-resolver/index.ts
src/Project/Sugcon/SugconNaSxa/src/lib/site-resolver/plugins/default.ts
src/Project/Sugcon/SugconNaSxa/src/lib/site-resolver/plugins/multisite.ts
src/Project/Sugcon/SugconNaSxa/src/lib/sitemap-fetcher/plugins/graphql-sitemap-service.ts
src/Project/Sugcon/SugconNaSxa/src/pages/[[...path]].tsx
src/Project/Sugcon/SugconNaSxa/src/pages/api/sitemap.ts

Upgrade JSS to version 21.2.2 in the NA SUG site to take advantage of the server-rendered XM Cloud Components feature.  
No

Upgrade JSS version

---

src/Project/Sugcon/SugconNaSxa/src/components/FEaaSWrapper.tsx

Additional changes to finalize upgrade to 22.2.2 JSS version
No

Update FEaaSWrapper to 22.2.2 version

---

src/Project/Sugcon/SugconAnzSxa/src/assets/app.scss
src/Project/Sugcon/SugconAnzSxa/src/assets/components/announcementbar.scss
src/Project/Sugcon/SugconAnzSxa/src/assets/components/cta.scss
src/Project/Sugcon/SugconAnzSxa/src/assets/components/fixed-width-container.scss
src/Project/Sugcon/SugconAnzSxa/src/assets/components/hero.scss
src/Project/Sugcon/SugconAnzSxa/src/assets/components/navigation.scss
src/Project/Sugcon/SugconAnzSxa/src/assets/components/organiserList.scss
src/Project/Sugcon/SugconAnzSxa/src/assets/components/sponsorList.scss
src/Project/Sugcon/SugconAnzSxa/src/components/Navigation.tsx
src/Project/Sugcon/SugconAnzSxa/src/components/Sugcon/AnnouncementBar.tsx
src/Project/Sugcon/SugconAnzSxa/src/components/Sugcon/CTA.tsx
src/Project/Sugcon/SugconAnzSxa/src/components/Sugcon/Hero.tsx
src/Project/Sugcon/SugconAnzSxa/src/components/Sugcon/OrganiserList.tsx
src/Project/Sugcon/SugconAnzSxa/src/components/Sugcon/SponsorList.tsx

Updated SUGCON ANZ to latest component versions

---

.github/workflows/CI-CD_SUGCON_ANZ.yml
.github/workflows/CI-CD_SUGCON_EU.yml
.github/workflows/CI-CD_SUGCON_India.yml

Some of the SUGCON Build definitions were still referencing the old separate build stages we have had for Staging & Prod. This PR fixes it.

Tidied SUGCON build definitions

---

src/Project/Sugcon/SugconAnzSxa/src/Layout.tsx
src/Project/Sugcon/SugconAnzSxa/src/assets/app.scss
src/Project/Sugcon/SugconAnzSxa/src/assets/components/cta.scss
src/Project/Sugcon/SugconAnzSxa/src/assets/components/hero.scss
src/Project/Sugcon/SugconAnzSxa/src/assets/components/organiserList.scss
src/Project/Sugcon/SugconAnzSxa/src/assets/components/sponsorList.scss
src/Project/Sugcon/SugconAnzSxa/src/components/Sugcon/CTA.tsx
src/Project/Sugcon/SugconAnzSxa/src/components/Sugcon/SponsorList.tsx
src/Project/Sugcon/SugconAnzSxa/src/pages/_document.tsx
src/Project/Sugcon/SugconNaSxa/src/assets/app.scss

In order to align branding with SUGCON NA and events landing page, making basic styling changes for first phase of the rebrand.
Testing on Vercel staging site: https://sugcon-anz-robearlam-sitecoretechnicalmarketing.vercel.app/

Rebrand SUGCON ANZ

---

src/Project/Sugcon/SugconAnzSxa/src/components/Sugcon/CTA.tsx
src/Project/Sugcon/SugconEuSxa/src/assets/app.scss
src/Project/Sugcon/SugconEuSxa/src/assets/components/cta.scss
src/Project/Sugcon/SugconEuSxa/src/assets/components/hero.scss
src/Project/Sugcon/SugconEuSxa/src/assets/components/organiserList.scss
src/Project/Sugcon/SugconEuSxa/src/assets/components/sponsorList.scss
src/Project/Sugcon/SugconEuSxa/src/components/Sugcon/CTA.tsx
src/Project/Sugcon/SugconEuSxa/src/components/Sugcon/SponsorList.tsx
src/Project/Sugcon/SugconEuSxa/src/pages/_document.tsx

Styling for SUGCON EU components updated to match NA and ANZ.
Tested on Vercel preview site: https://sugcon-eu-robearlam-sitecoretechnicalmarketing.vercel.app/

Rebrand SUGCON EU

---

src/Project/Sugcon/SugconEuSxa/src/assets/components/sponsorList.scss
src/Project/Sugcon/SugconIndiaSxa/src/assets/app.scss
src/Project/Sugcon/SugconIndiaSxa/src/assets/components/cta.scss
src/Project/Sugcon/SugconIndiaSxa/src/assets/components/hero.scss
src/Project/Sugcon/SugconIndiaSxa/src/assets/components/organiserList.scss
src/Project/Sugcon/SugconIndiaSxa/src/assets/components/sponsorList.scss
src/Project/Sugcon/SugconIndiaSxa/src/components/Sugcon/CTA.tsx
src/Project/Sugcon/SugconIndiaSxa/src/components/Sugcon/SponsorList.tsx
src/Project/Sugcon/SugconIndiaSxa/src/pages/_document.tsx

Changed components and styles to match with other SUGCON sites
Tested on Vercel preview site: https://sugcon-india-robearlam-sitecoretechnicalmarketing.vercel.app/

Rebrand SUGCON India

---

src/Feature/Selections/rendering/Models/Apply/ApplicationFormModel.cs
src/Feature/Selections/rendering/ViewComponents/Apply/ApplicationFormViewComponent.cs

Fixed nullref occurring when editing a Contribution with related products
Local Machine
Manual UI test

Fixed Nullref on ContributionProductIds

---

up.ps1

Move initial env variable check above code that fetches env var values. 
Catching this case sooner rather than later provides a more helpful error message.
Ran up.ps1 script.

Minor improvement to up.ps1

---

src/Feature/Selections/rendering/ViewComponents/Any/MyProfilesFormViewComponent.cs

+ API response code changed from OK to CREATED
Fixes #300 
Manual UI Testing
Local Machine

Fix #300 Add Profile Links

---

.env.template
.github/workflows/build_DotNet.yml
.github/workflows/deploy_azureWebapp.yml
.github/workflows/deploy_xmCloud.yml
Packages.props
README.md
sitecore.json
src/Feature/BasicContent/rendering/MVP.Feature.BasicContent.Rendering.csproj
src/Feature/Navigation/rendering/Mvp.Feature.Navigation.Rendering.csproj
src/Feature/People/rendering/Mvp.Feature.People.Rendering.csproj
src/Feature/Selections/rendering/Mvp.Feature.Selections.Rendering.csproj
src/Feature/Social/rendering/Mvp.Feature.Social.Rendering.csproj
src/Feature/User/rendering/Mvp.Feature.User.Rendering.csproj
src/Foundation/Configuration/rendering/Mvp.Foundation.Configuration.Rendering.csproj
src/Foundation/DataFetching/rendering/Mvp.Foundation.DataFetching.Rendering.csproj
src/Project/MvpSite/rendering/Mvp.Project.MvpSite.Rendering.csproj

Upgrade to .net 8 based on request
Tested in VS 2022 by building the solution as well as running .\up.ps1

#286: upgrade to .net 8 and added edge cli plugin for future

---

down.ps1

This fixes #318 
down.ps1 uses docker-compose v1.  It gives an error that the command cannot be found.
Changed to docker compose v2.
Successfully ran down.ps1

Change docker compose to v2

---

.env.template
.github/workflows/CI-CD_SUGCON_24.yml
.github/workflows/build_NextJs.yml
src/Project/Sugcon2024/Sugcon/package.json
src/Project/Sugcon2024/Sugcon/src/components/Hero/Hero.tsx

Added Github Actions for Sugcon 2024 project

---

src/Project/Sugcon2024/items/SiteShared/Shared/Presentation/Page Designs.yml
src/Project/Sugcon2024/items/SiteShared/Shared/Presentation/Page Designs/Homepage.yml
src/Project/Sugcon2024/items/SiteShared/Shared/Presentation/Page Designs/Page.yml
src/Project/Sugcon2024/items/SiteShared/Shared/Presentation/Partial Designs/Footer.yml
src/Project/Sugcon2024/items/SiteShared/Shared/Presentation/Partial Designs/Generic Page.yml
src/Project/Sugcon2024/items/SiteShared/Shared/Presentation/Partial Designs/Header.yml
src/Project/Sugcon2024/items/SiteShared/Shared/Presentation/Placeholder Settings/Partial Design/Footer.yml
src/Project/Sugcon2024/items/SiteShared/Shared/Presentation/Placeholder Settings/Partial Design/Generic Page.yml
src/Project/Sugcon2024/items/SiteShared/Shared/Presentation/Placeholder Settings/Partial Design/Header.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Generic Page.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Generic Page/Content.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Generic Page/Content/Content.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Generic Page/Content/Title.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Generic Page/__Standard Values.yml

1. https://trello.com/c/p3fOl8Wg/15-create-header-partial-design
2. https://trello.com/c/eMSdzAAn/16-create-footer-partial-design
3. https://trello.com/c/WKLffFGQ/25-create-page-partial-design
4. https://trello.com/c/edFCdeJa/65-create-page-designs
Items were created on local and serialized.

Create partial and page design items

---

CONTRIBUTING.md
docs/PULL_REQUESTS.md

We've got a multi-disciplinary team working on the SUGCON redesign project.  I want to get some guidelines in place for how we will be submitting and reviewing changes to this code base.  While the immediate intent of this documentation is for the SUGCON redesign, it should be applicable for the rest of the code base as well.
This is documentation only.  Will be reviewing with the larger team during standup.

Pull request guidelines for SUGCON redesign team

---

src/Project/Sugcon2024/Sugcon/src/components/Hero/Hero.tsx
src/Project/Sugcon2024/items/Media/Sugcon2024/Basic Components.yml
src/Project/Sugcon2024/items/PlaceholderSettings/Sugcon2024/Basic Components.yml
src/Project/Sugcon2024/items/Renderings/Sugcon2024/Basic Components.yml
src/Project/Sugcon2024/items/Renderings/Sugcon2024/Basic Components/Hero.yml
src/Project/Sugcon2024/items/SiteShared/Shared/Presentation/Available Renderings/Page Content.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Hero Folder.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Hero Folder/__Standard Values.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Hero.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Hero/Content.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Hero/Content/CallToAction.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Hero/Content/Date.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Hero/Content/Description.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Hero/Content/Image.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Hero/Content/Title.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Rendering Parameters.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Rendering Parameters/Hero.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Rendering Parameters/Hero/__Standard Values.yml

https://trello.com/c/FNe2q3P1/28-create-hero-component
Create the default variation of the hero component
1. The tsx file follows a similar pattern to the OOTB promo component
2. The UI will hide date, description and call to action fields if they are not set
3. The UI fits desktop, tablet and mobile.
4. The link correctly opens in the same tab or a new tab as specified in the CTA link field
5. The alt text from the image is correctly added to the img tag.

Create Hero Component

---

src/Project/Sugcon2024/Sugcon/package.json

We want to deploy the Storybook site to Vercel that contains all of the new components for the SUGCON site redesign.  @lovesitecore and I ran into an issue when deploying Storybook which is resolved after implementing the steps detailed here from Rob Ahnemann: https://rockpapersitecore.com/2023/06/error-cannot-find-module-src-temp-config-when-running-storybook-7/
By adding an npm script with `pre` prepended, we guarantee that this script will be executed before the task that we want to run: `build-storybook`.
https://docs.npmjs.com/cli/v9/using-npm/scripts#pre--post-scripts
I've implemented this change locally and deployed to my Hobby Vercel account with great success: https://xm-cloud-introduction.vercel.app/

Storybook: Added bootstrap command needed to deploy Storybook to Vercel

---

src/Project/Sugcon2024/Sugcon/src/components/Hero/Hero.stories.ts
src/Project/Sugcon2024/Sugcon/src/components/Hero/Hero.tsx

Fix linting issues on Hero Component and related Storybook file.

---

.github/workflows/CI-CD_SUGCON_24_STORYBOOK.yml
.github/workflows/build_NextJs_Storybook.yml

Added Github Actions for Storybook to Vercel

---

src/Project/Sugcon2024/Sugcon/.gitignore
src/Project/Sugcon2024/Sugcon/package-lock.json

Ignore Storybook Build files.

---

src/Project/Sugcon2024/Sugcon/src/Theme.ts
src/Project/Sugcon2024/Sugcon/src/components/Basic Components/Hero.tsx

Fixing up a few more notes from our designer and adding button hovers
Small updates for the Hero component for SUGCON 2024
Testing locally with components on a page and with Storybook

SUGCON24 Hero Updates + Button Hover

---

src/Feature/People/rendering/PeopleFinder/MvpFinder.cs

Fixes searching with spaces
#345 
Manual UI Test
Local Machine

Fix searching with spaces

---

src/Project/MvpSite/rendering/Views/Shared/_Layout.cshtml
src/Project/MvpSite/rendering/wwwroot/style/ee.css

Forced EE Header to join the normal page layout flow
#132 
Manual UI Test
Local Machine

Fix EE Header

---

src/Project/MvpSite/rendering/Middleware/EnsureAcceptLanguageHeaderMiddleware.cs

Force AcceptLanguage header to be valid (we only support 1 language atm)
#179 
Manual UI Test
NGROK to local machine using an iPhone with the issue

#179 Workaround

---

src/Project/Sugcon2024/Sugcon/src/components/Basic Components/Link.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Basic Components/Link.stories.ts
src/Project/Sugcon2024/items/Modules/Sugcon2024/Basic Components/Basic Components Headless Site Setup/Add Links Data Item.yml
src/Project/Sugcon2024/items/Renderings/Sugcon2024/Basic Components/Link.yml
src/Project/Sugcon2024/items/SiteShared/Shared/Data/Links.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Link Folder.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Link Folder/__Standard Values.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Link.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Link/Content.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Link/Content/Link.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Rendering Parameters/Link.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Rendering Parameters/Link/__Standard Values.yml

https://trello.com/c/3DY0r2cg/24-create-or-reuse-contact-us-link-component
Created a basic link component since one is not provided OOTB
1. Component has been added to the page 
2. Component has been tested with and without a datasource

Add basic link component

---

src/Project/Sugcon2024/Sugcon/src/components/Basic Components/Person.tsx
src/Project/Sugcon2024/Sugcon/src/components/List Components/PeopleGrid.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/List Components/PeopleGrid.stories.ts
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Rendering Parameters/People Grid/Layout/Alphabetize.yml

https://trello.com/c/llPZzrxf/38-create-speaker-component
Updating the People Grid component
1. Make the image and name clickable to open a modal showing the biography
2. Add a rendering parameter to display the people in alphabetical order
1. Tested the display with and without the Link To Bio option selected
2. Tested the display with and without the Alphabetize option selected
3. Tested UI on mobile, tablet and desktop.

Update People Grid to link to bio and alphabetize

---

src/Project/Sugcon2024/Sugcon/src/components/Basic Components/VideoText.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Basic Components/VideoText.stories.ts
src/Project/Sugcon2024/items/Modules/Sugcon2024/Basic Components/Basic Components Headless Site Setup/Add Video and Texts Data Item.yml
src/Project/Sugcon2024/items/Renderings/Sugcon2024/Basic Components/Video and Text.yml
src/Project/Sugcon2024/items/SiteShared/Shared/Data/Video and Text.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Rendering Parameters/Video and Text.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Rendering Parameters/Video and Text/__Standard Values.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Video and Text Folder.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Video and Text Folder/__Standard Values.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Video and Text.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Video and Text/Content.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Video and Text/Content/Headline.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Video and Text/Content/Text.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Video and Text/Content/TextHeadline.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Video and Text/Content/YoutubeVideoId.yml

https://trello.com/c/Gbgdvwy5/32-create-video-text-component
Create a component for video and text
1.  Tested on mobile, tablet and desktop
2. Tested with and without a headline
3. Tested with and without a text headline

Create video text component

---

src/Project/Sugcon/SugconNaSxa/package-lock.json
src/Project/Sugcon2024/Sugcon/.storybook/main.ts
src/Project/Sugcon2024/Sugcon/.storybook/preview.tsx
src/Project/Sugcon2024/Sugcon/src/assets/basic/_navigation.scss
src/Project/Sugcon2024/Sugcon/src/assets/sass/abstracts/vars/_colors.scss
src/Project/Sugcon2024/Sugcon/src/components/Navigation.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Basic Components/Navigation.stories.tsx

Updates to the Navigation component to support the design for SUGCON 2024.  Also updated Storybook to pull in our theme SCSS and incorporate it into the components.
Need to build out Desktop and Mobile navigation for the sites
Tested locally in Sitecore as well as Storybook

Navigation Updates SUGCON2024

---

src/Project/Sugcon2024/Sugcon/src/assets/sass/components/_component-action-banner.scss
src/Project/Sugcon2024/Sugcon/src/assets/sass/components/index.scss
src/Project/Sugcon2024/Sugcon/src/components/Basic Components/ActionBanner.tsx
src/Project/Sugcon2024/items/Modules/Sugcon2024/Basic Components/Basic Components Headless Site Setup/Add ActionBanners Data Item.yml
src/Project/Sugcon2024/items/Renderings/Sugcon2024/Basic Components/ActionBanner.yml
src/Project/Sugcon2024/items/SiteEU/EU/Data/Action Banners.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/ActionBanner.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/ActionBanner/ActionBanner Folder.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/ActionBanner/ActionBanner Folder/__Standard Values.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/ActionBanner/ActionBanner.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/ActionBanner/ActionBanner/Content.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/ActionBanner/ActionBanner/Content/CallToAction.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/ActionBanner/ActionBanner/Content/Text.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/ActionBanner/ActionBanner/Content/Title.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Rendering Parameters/ActionBanner.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Rendering Parameters/ActionBanner/__Standard Values.yml

Added the Action Banner component, coming with a Title, Text and CallToAction Link. 
It can be found under Basic Components. 
Open: Polishment in Styles - but we're concentrating on functionality for now :)
Locally in the frontend app and in local Pages, currently editing possibility for the Link doesn't work.
- added rendering and related items
- added ActionBanner.tsx andrelated scss file

added Action Banner compoent and related items

---

src/Project/Sugcon2024/Sugcon/src/components/Basic Components/ActionBanner.tsx
src/Project/Sugcon2024/Sugcon/src/components/Events/Agenda.tsx

formatted Agenda.tsx and ActionBanner.tsx because prettier was throwing an error. 
with running npm run build
- [x ] Bug fix (non-breaking change which fixes an issue)

formatted for the happiness of prettier

---

src/Project/Sugcon2024/Sugcon/src/components/Basic Components/Logo.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Basic Components/Logo.stories.ts
src/Project/Sugcon2024/items/SiteShared/Shared/Presentation/Partial Designs/Footer.yml
src/Project/Sugcon2024/items/SiteShared/Shared/Presentation/Partial Designs/Header.yml

1. Setup the shared Header and Footer partial design Logo components to pull their datasources from `query:$site/Data/Images/Logos/`
2. Copied the Image.tsx component and renamed to Logo.tsx
3. Added the Storybook component (not tested)
I've loaded up the partial designs and the SUGCONEU 2024 Homepage in Experience Editor to validate that the component renders as expected.

Logo Datasource and UI Improvements

---

src/Project/Sugcon2024/Sugcon/src/components/Basic Components/Logo.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Basic Components/Logo.stories.ts

[Logo Storybook](https://sugcon24-storybook.vercel.app/?path=/docs/components-logo--docs)
Added a nullcheck for `sitecoreContext` and tweaked the image sizing.

Logo component not rendering in Storybook

---

src/Project/Sugcon2024/Sugcon/src/components/Sponsors/SponsorListing.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/List Components/SponsorListing.Error.stories.ts
src/Project/Sugcon2024/Sugcon/src/stories/components/List Components/SponsorListing.ImageOnly.stories.ts
src/Project/Sugcon2024/Sugcon/src/stories/components/List Components/SponsorListing.stories.ts

- Variant updates
- EE Support
- Add stories for storybook
Local

Add EE support, variant updates and stories for sponsor list component

---

src/Project/Sugcon2024/Sugcon/src/components/Sponsors/SponsorListing.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/List Components/SponsorListing.Default.stories.ts
src/Project/Sugcon2024/Sugcon/src/stories/components/List Components/SponsorListing.Error.stories.ts
src/Project/Sugcon2024/Sugcon/src/stories/components/List Components/SponsorListing.ImageOnly.stories.ts
src/Project/Sugcon2024/items/SiteEU/EU/Presentation/Headless Variants/Sponsor Listing/LogoWithPopup.yml

This PR adds a variant 'Logo with popup' to the Sponsor Listing component
Also includes update Storybook stories
Local

Update sponsor listing with variant 'Logo with popup'

---

src/Project/Sugcon2024/Sugcon/src/components/Sponsors/SponsorListing.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/List Components/SponsorListing.ImageWithPopup.stories.ts

This PR adds the Storybook story for the SponsorListing > Logo with popup variant
Local

Add missing story for sponsorlisting

---

src/Project/Sugcon2024/Sugcon/src/components/Basic Components/Event.tsx
src/Project/Sugcon2024/Sugcon/src/components/Basic Components/EventTeaser.tsx
src/Project/Sugcon2024/Sugcon/src/components/Basic Components/Link.tsx
src/Project/Sugcon2024/Sugcon/src/components/Basic Components/Person.tsx
src/Project/Sugcon2024/Sugcon/src/components/Basic Components/TextImage.tsx
src/Project/Sugcon2024/Sugcon/src/components/Basic Components/VideoText.tsx
src/Project/Sugcon2024/Sugcon/src/components/List Components/PeopleGrid.tsx
src/Project/Sugcon2024/items/Branches/Sugcon2024/Basic Components.yml
src/Project/Sugcon2024/items/Branches/Sugcon2024/Basic Components/Available Headless Basic Components Renderings/_name.yml
src/Project/Sugcon2024/items/Branches/Sugcon2024/List Components.yml
src/Project/Sugcon2024/items/Branches/Sugcon2024/List Components/Available Headless List Components Renderings.yml
src/Project/Sugcon2024/items/Branches/Sugcon2024/List Components/Available Headless List Components Renderings/_name.yml
src/Project/Sugcon2024/items/Modules/Sugcon2024/Basic Components/Basic Components Headless Site Setup/Add Text and Images Data Item.yml
src/Project/Sugcon2024/items/Renderings/Sugcon2024/List Components/Event Teaser.yml
src/Project/Sugcon2024/items/SiteEU/EU/Data/Events.yml
src/Project/Sugcon2024/items/SiteEU/EU/Data/People.yml
src/Project/Sugcon2024/items/SiteEU/EU/Data/Text and Image.yml
src/Project/Sugcon2024/items/SiteEU/EU/Data/Video and Text.yml
src/Project/Sugcon2024/items/SiteShared/Shared/Data/Text and Image.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Event Teaser Folder/__Standard Values.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Rendering Parameters/Event Teaser/__Standard Values.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Event Teaser Folder.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Event Teaser Folder/__Standard Values.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Event Teaser.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Event Teaser/Content.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Event Teaser/Content/Events.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Event Teaser/Content/Headline.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Rendering Parameters/Event Teaser.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Rendering Parameters/Event Teaser/__Standard Values.yml

Add EE/Pages support for previously built components
- Text and Image
- Video and Text
- People Grid
- Event Teaser
- Link
-Tested to ensure all fields are editable in EE
-Tested to ensure that empty, non-required fields show in EE, but are hidden from the frontend

Enable EE/Pages.  Include settings items.

---

src/Project/Sugcon2024/Sugcon/src/basics/ButtonLink.tsx
src/Project/Sugcon2024/items/Renderings/Sugcon2024/Basic Components/Venue.yml
src/Project/Sugcon2024/items/SiteEU/EU/Data/Venue.yml

- Corrects datasource template query
- Adds data folder to EU site
- EE support for ButtonLink component
Local

Update venue component

---

src/Project/Sugcon2024/Sugcon/package.json
src/Project/Sugcon2024/Sugcon/public/speakers.html
src/Project/Sugcon2024/Sugcon/src/components/Basic Components/Person.tsx
src/Project/Sugcon2024/Sugcon/src/components/List Components/SpeakersGrid.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/List Components/SpeakerGrid.stories.ts
src/Project/Sugcon2024/items/SiteEU/EU/Data/Speakers Grid.yml
src/Project/Sugcon2024/items/SiteShared/Shared/Data/Speakers Grid.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Rendering Parameters/Speakers Grid.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Rendering Parameters/Speakers Grid/Layout.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Rendering Parameters/Speakers Grid/Layout/Alphabetize.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Rendering Parameters/Speakers Grid/Layout/Columns.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Rendering Parameters/Speakers Grid/Layout/DisplaySocialLinks.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Rendering Parameters/Speakers Grid/Layout/LinkToBio.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Rendering Parameters/Speakers Grid/__Standard Values.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Speakers Grid Folder.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Speakers Grid Folder/__Standard Values.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Speakers Grid.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Speakers Grid/Content.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Speakers Grid/Content/Headline.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Speakers Grid/Content/SessionizeSpeakerUrl.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Speakers Grid/Content/SessionsListTitle.yml

https://trello.com/c/llPZzrxf/38-create-speaker-component
Create a speaker component that can read from sessionize.
- This component is a modified clone of the people grid.  
- 
- You can change the number of columns, alphabetize, set a background color
- The heading field can be edited via EE
- It has been tested on mobile and desktop
- It gives a console error if it cannot read from the sessionize url
- It only displays the heading if the sessionize url is false or cannot read the data.

Add Speakers component to read data from Sessionize

---

src/Project/Sugcon2024/Sugcon/src/stories/components/Basic Components/Accordion.stories.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Basic Components/ActionBanner.stories.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Basic Components/EventHero.stories.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Basic Components/EventTeaser.stories.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Basic Components/HomepageHero.stories.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Basic Components/JustificationLetterHero.stories.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Basic Components/Link.stories.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Basic Components/Logo.stories.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Basic Components/Navigation.stories.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Basic Components/Person.stories.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Basic Components/TextImage.stories.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Basic Components/Venue.stories.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Basic Components/VideoText.stories.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Events/Agenda.stories.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Events/Sessions.stories.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/List Components/IconLinkList.stories.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/List Components/PeopleGrid.stories.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Sponsors/SponsorListing.Default.stories.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Sponsors/SponsorListing.Error.stories.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Sponsors/SponsorListing.ImageOnly.stories.tsx
src/Project/Sugcon2024/Sugcon/src/stories/components/Sponsors/SponsorListing.ImageWithPopup.stories.tsx

1. Added missing stories
2. Organized the Storybook sections according to the component folder structure 
I ran Storybook locally and verified each of the components renders.

Storybook Cleanup

---

src/Project/Sugcon2024/items/_roles/Sugcon2024/Site Admin.yml
src/Project/Sugcon2024/items/_roles/Sugcon2024/Site Author.yml
src/Project/Sugcon2024/items/_roles/Sugcon2024/Site Collection Admin.yml
src/Project/Sugcon2024/items/_roles/Sugcon2024/Site Collection Author.yml
src/Project/Sugcon2024/items/_roles/Sugcon2024/Site Collection Designer.yml
src/Project/Sugcon2024/items/_roles/Sugcon2024/Site Collection Member.yml
src/Project/Sugcon2024/items/_roles/Sugcon2024/Site Designer.yml
src/Project/Sugcon2024/items/_roles/Sugcon2024/Site Member.yml
src/Project/Sugcon2024/roles.module.json

Created Roles for authors based on Standard SXA Roles for Site Collection and Site
Roles have been serialized and a new modules.json file is provided.
tested on Prod. Roles have been serialized from Prod.

added new module.json file for roles and serialized roles.

---

src/Project/Sugcon2024/Sugcon/src/assets/sass/components/_component-action-banner.scss
src/Project/Sugcon2024/Sugcon/src/components/Basic Components/Hero.tsx
src/Project/Sugcon2024/Sugcon/src/components/Basic Components/TextImage.tsx
src/Project/Sugcon2024/Sugcon/src/components/Basic Components/Venue.tsx
src/Project/Sugcon2024/Sugcon/src/components/Basic Components/VideoText.tsx
src/Project/Sugcon2024/Sugcon/src/components/List Components/Accordion.tsx
src/Project/Sugcon2024/Sugcon/src/components/List Components/PeopleGrid.tsx

We need to get the components in alignment per the design
I packed up the content from production and tried to update as many components as I could to get a good step forward in matching the design provided.
Running it locally via Experience Editor and a side browser to verify all incremental updates

SUGCON 2024 Component Design Update

---

src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Accordion.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Accordion/__Standard Values.yml

1. Add accordion element as insert option for accordion
2. Change query for elements field on accordion to only display child items.

Update accordion to have elements as children

---

src/Project/Sugcon2024/items/Renderings/Sugcon2024/List Components/Speakers Grid.yml

Add speaker grid rendering

---

src/Project/Sugcon2024/Sugcon/src/components/Basic Components/TextImage.tsx

UI updates needed to match the provided design
- Updating margins and layouts to match the design provided.  
- Updating the image to only show border radius outside of mobile.
- Making the max image size larger to 500px to match design
Locally testing against production content and image

SUGCON24 TextImage UI Updates

---

src/Project/Sugcon2024/Sugcon/src/components/Basic Components/Event.tsx

Removing the bottom of the conversation bubble on mobile per design note
Hiding the box on mobile
Locally with production content

SUGCON24 - Event Teaser Mobile Update

---

src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Person.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Person/__Standard Values.yml

https://trello.com/c/uZSEFYxa/111-person-item-use-name-token-for-person-templatt-in-name-field
The standard values were not correctly linked to the person template.
Recreate standard values item
Create new person item
Validate that the name field is populated with the name of the newly created item.

Recreate standard values

---

src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Event Teaser/Content/Events.yml

https://trello.com/c/uaA9dfK7/35-create-event-teaser-component
I validated that the events field populates correctly with the updated query.

Update source query

---

src/Project/Sugcon2024/Sugcon/src/Layout.tsx
src/Project/Sugcon2024/items/Templates/Sugcon2024/Base Templates/_OG Tags.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Base Templates/_OG Tags/Open Graph Tags.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Base Templates/_OG Tags/Open Graph Tags/OGDescription.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Base Templates/_OG Tags/Open Graph Tags/OGImage.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Base Templates/_OG Tags/Open Graph Tags/OGTitle.yml
src/Project/Sugcon2024/items/Templates/Sugcon2024/Base Templates/_OG Tags/Open Graph Tags/OGType.yml

https://trello.com/c/PA8gZfz9/83-og-tags
1. I added a new base template for _ogtags
2. I added the _ogtags to the _basepage (which is used by home page and generic page)
3. I added the tags to the layout.tsx file
4. I added a canonical tag to the layout.tsx file.
5. If a field for a page is empty, the tag will render with empty content in the html

Add open graph tags

---

src/Project/Sugcon2024/Sugcon/src/Layout.tsx
src/Project/Sugcon2024/items/Templates/Sugcon2024/Base Templates/_OG Tags/Open Graph Tags/OGImage.yml

Changed the OGImage field from single line text to image.
Set the property on a page and ensure that the correct image url shows in the OGImage meta tag.

Change OGImage to ImageField

---

src/Project/Sugcon2024/Sugcon/src/Theme.ts
src/Project/Sugcon2024/Sugcon/src/components/Basic Components/Logo.tsx
src/Project/Sugcon2024/Sugcon/src/components/Navigation.tsx
src/Project/Sugcon2024/Sugcon/src/components/Templates/Header.tsx
src/Project/Sugcon2024/Sugcon/src/components/Templates/LayoutConstants.ts
src/Project/Sugcon2024/Sugcon/src/stories/templates/Header.stories.tsx

https://trello.com/c/AJZ4XbDG/108-header-alignment-styling
This fixes the header spacing, font sizes across breakpoints, mobile button size, etc.
Local instance and stroybook.

Header Spacing and Font Sizes

---

src/Project/Sugcon2024/Sugcon/package-lock.json
src/Project/Sugcon2024/Sugcon/src/Theme.ts
src/Project/Sugcon2024/Sugcon/src/assets/basic/_container.scss
src/Project/Sugcon2024/Sugcon/src/components/Container.tsx
src/Project/Sugcon2024/Sugcon/src/components/Events/Agenda.tsx
src/Project/Sugcon2024/Sugcon/src/components/Events/Sessions.tsx
src/Project/Sugcon2024/Sugcon/src/components/List Components/Accordion.tsx
src/Project/Sugcon2024/Sugcon/src/components/Structure/PageTitle.tsx

Fixing layout issues best I can for Agenda and Session components.  Fixing eslint swr errors.  Fixing PageTitle component layout.  Updating Container component for breakpoints.  Adding Accordion theme.
Local dev server and storybook.

Fixing layout issues best I can for Agenda and Session components.

---

src/Project/Sugcon2024/Sugcon/src/assets/basic/_footer.scss

https://trello.com/c/xDFHJWvS
Add a width tag so the footer image is full screen width (override the max-width property which caused the background to show through).
Tested by using the browser to zoom in and out to various sizes.

Make footer image full width

---

src/Project/Sugcon2024/Sugcon/src/components/Sponsors/SponsorListing.tsx

This PR addresses the alignment issues with the sponsor component. It now uses the LayoutFlex component to be consistent with other components
Local

SUGCON24: Use LayoutFlex for alignment of sponsorlist component

---

src/Project/Sugcon2024/items/SiteEU/EU/Presentation/Available Renderings/Basic Components.yml
src/Project/Sugcon2024/items/SiteEU/EU/Presentation/Available Renderings/List Components.yml

We were missing some available renderings for Basic Components and List Components
The components are now available from the Toolbox in Pages.

SUGCON24 EU: Setup missing components in Available Renderings.

---

src/Project/Sugcon2024/Sugcon/src/Theme.ts
src/Project/Sugcon2024/Sugcon/src/assets/sass/components/_component-container.scss
src/Project/Sugcon2024/Sugcon/src/assets/sass/components/index.scss
src/Project/Sugcon2024/Sugcon/src/assets/sass/components/people-grid/_people-grid-container.scss
src/Project/Sugcon2024/Sugcon/src/assets/sass/components/people-grid/index.scss
src/Project/Sugcon2024/Sugcon/src/assets/sass/components/speakers-grid/_speakers-grid-container.scss
src/Project/Sugcon2024/Sugcon/src/assets/sass/components/speakers-grid/index.scss
src/Project/Sugcon2024/Sugcon/src/components/Basic Components/Person.tsx
src/Project/Sugcon2024/Sugcon/src/components/List Components/PeopleGrid.tsx
src/Project/Sugcon2024/Sugcon/src/components/List Components/SpeakersGrid.tsx

Bug fixes: Updates to Person, PeopleGrid, and SpeakersGrid components, Chakra Theme, and container css.
Local dev and storybook.

Updates to Person, PeopleGrid, and SpeakersGrid components, Chakra Theme, and container css.

---

src/Project/Sugcon2024/Sugcon/src/components/CdpPageView.tsx

There was a console log error due to a missing cdp client key.  This pr disables cdp if the client key is not set or if the environment is development.
Ensure that the console error is resolved if the client key is empty.

Check CDP Configuration

---

src/Project/Sugcon2024/Sugcon/src/components/Sponsors/SponsorListing.tsx

https://trello.com/c/lAxUf5fB
Set different max width for mobile vs meduium+

Make full width on mobile

---

src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/Icon Link List/Icon Link List Folder/__Standard Values.yml

https://trello.com/c/cX3oeGbY/146-icon-link-list-insert-options-missing-the-icon-link-list-template-or-branch-in-shared-eu-and-india-site?filter=label:Bug

Set insert options

---

src/Project/Sugcon2024/items/Templates/Sugcon2024/List Components/People Grid/Content/People.yml

The People Grid Component showed all people items created within the whole content tree. I limited that to the site.

Changed Source to only look for People maintained within the site.

---

src/Project/Sugcon2024/Sugcon/src/assets/sass/components/index.scss
src/Project/Sugcon2024/Sugcon/src/assets/sass/components/sponsors/_sponsor.scss
src/Project/Sugcon2024/Sugcon/src/assets/sass/components/sponsors/index.scss
src/Project/Sugcon2024/Sugcon/src/components/Sponsors/SponsorListing.tsx

Sponsor Component incl. Variations did not meet requirements. The component got reworked. to meet requirements. This includes all existing variants. 
the layout got simplified by using chakra <SimpleGrid> and <Box> elements for Each GridChild. Also Responsive Design has been taken into account.
this has been tested locally in EE preview.

Fix sponor component

---

README.md

This PR updates the documentation to reflect the recent change where the SUGCON websites have been organized into a single multisite instance within the Sugcon2024 folder. The updated docs now provide accurate guidance on how to work with the new multisite setup.

Updated SUGCON documentation for multisite setup

---

headapps/MvpSite/MvpSite.Rendering/Attributes/HttpsUrlAttribute.cs

Fixed validation of https links
Currently valid values are not being accepted
Manual UI test
Local Docker

Fixed https uri validation

---

headapps/MvpSite/MvpSite.Rendering/wwwroot/sass/components/hero.scss
headapps/MvpSite/MvpSite.Rendering/wwwroot/sass/components/people/directory.scss
headapps/MvpSite/MvpSite.Rendering/wwwroot/sass/components/people/profile.scss

Removing old brand lollipop

---

authoring/items/Mvp/Feature.Selections/items/templates/Selections/Admin/ScoreCards/ScoreCards/Table Headers/SentimentsTableHeader.yml
authoring/items/Mvp/Feature.Selections/items/templates/Selections/Admin/ScoreCards/ScoreCards/__Standard Values.yml
headapps/MvpSite/Directory.Packages.props
headapps/MvpSite/MvpSite.Rendering/Models/Admin/ScoreCardsModel.cs
headapps/MvpSite/MvpSite.Rendering/Views/Shared/Components/AdminScoreCardDetail/Default.cshtml
headapps/MvpSite/MvpSite.Rendering/Views/Shared/Components/AdminScoreCards/Default.cshtml

Adds the sentiment score summary to the score cards overview.
Tamas needs these during final reviews.
Manual UI Tests
Local Docker

Scorecards overview now displays sentiment information

---

authoring/items/Mvp/Feature.Selections/items/renderings/Selections/Admin/Users/MergeUsers.yml
headapps/MvpSite/MvpSite.Rendering/Extensions/ICollectionExtensions.cs
headapps/MvpSite/MvpSite.Rendering/Extensions/RenderingEngineOptionsExtensions.cs
headapps/MvpSite/MvpSite.Rendering/Models/Admin/MergeUsersModel.cs
headapps/MvpSite/MvpSite.Rendering/ViewComponents/Admin/MergeUsersViewComponent.cs
headapps/MvpSite/MvpSite.Rendering/Views/Shared/Components/AdminMergeUsers/Default.cshtml

Added a visual component for admins to be able to merge users easily
Not all admins are capable of using the API directly and need a UI to execute the task of merging users.
Manual UI Testing
Local Docker

Added component for merging users

---

headapps/MvpSite/MvpSite.Rendering/Views/Shared/Components/Profile/Default.cshtml
headapps/MvpSite/MvpSite.Rendering/Views/Shared/Components/Profile/_Titles.cshtml

Introduces the images for title badges again
In restyling the images were lost
Manual UI Testing
Local Docker

Fixes badge images missing from profile

---

authoring/items/Mvp/Project.MvpSite/items/content/MvpSite/Home.yml
authoring/items/Mvp/Project.MvpSite/items/content/MvpSite/Home/About.yml
authoring/items/Mvp/Project.MvpSite/items/content/MvpSite/Home/Application.yml
authoring/items/Mvp/Project.MvpSite/items/content/MvpSite/Home/Become-an-mvp.yml
authoring/items/Mvp/Project.MvpSite/items/content/MvpSite/Home/Benefits.yml
authoring/items/Mvp/Project.MvpSite/items/content/MvpSite/Home/Contact.yml
authoring/items/Mvp/Project.MvpSite/items/placeholders/MvpSite/Header Signin.yml
authoring/items/Mvp/Project.MvpSite/items/templates/MvpSite/Page/__Standard Values.yml

Update the Page template standard values, and the renderings settings for pages that have overridden those values to setup the header matching Sitecore.com

Updated Header settings for Page StandardValues and pages renderings

---

authoring/items/Mvp/Feature.Selections/items/templates/Selections/Apply/ApplicationForm/Contributions Limit.yml
authoring/items/Mvp/Feature.Selections/items/templates/Selections/Apply/ApplicationForm/Contributions Limit/ContributionMaxLimitMessage.yml
authoring/items/Mvp/Feature.Selections/items/templates/Selections/Apply/ApplicationForm/Contributions Limit/ContributionMinLimitMessage.yml
authoring/items/Mvp/Feature.Selections/items/templates/Selections/Apply/ApplicationForm/Contributions Limit/MaxContributions.yml
authoring/items/Mvp/Feature.Selections/items/templates/Selections/Apply/ApplicationForm/Contributions Limit/MinContributions.yml
headapps/MvpSite/MvpSite.Rendering/Models/Apply/ApplicationFormModel.cs
headapps/MvpSite/MvpSite.Rendering/ViewComponents/Apply/ApplicationFormViewComponent.cs

Description / Motivation
- Prevents users from submitting the applications if fewer than 3 contributions are added.
- Prevents users from adding more than 30 contributions.
- Displaying appropriate error message and redirects to the Contributions page when validates fails.
How Has This Been Tested?
- Manually tested submissions with 0,2,3 and more than 30 contributions.
- Verified error messages appear correctly.
Closes #556

Contribution Limit bug fixes
