Sitecore/XM-Cloud-Introduction

src/Project/Sugcon/SugconAnzSxa/src/components/SXA/Navigation.tsx
Navigation collapses for smaller screens. Additional styling may be desired. 
Also collapse styling does not apply properly if opened then screen size changes
Steps to reproduce:
1. Shrink screen to where navbar hamburger appears.
2. Open the navbar by clicking the hamburger
3. Increase screen size until hamburger disappears 
4. Items will still be in column format and not shift to row.
This should only happen if you open nav and then increase the screen size,so not huge concern.
=> Added navigation toggle to work on smaller screens

src/Project/Sugcon/SugconAnzSxa/src/Layout.tsx, src/Project/Sugcon/SugconEuSxa/src/Layout.tsx
Attempt to fix page title display by accessing 'Title' using field name in Sitecore. The current code only displays the fallback 'Page' on every request, likely because the field name specified in the logic is wrong.
=> Updating pageTitle to Title

src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Data/SponsorLists/Video Recording sponsor.yml, src/Project/Sugcon/items/content/Sugcon/SugconAnzSxa/Home/Sponsors.yml
The extra sponsor list categories copied over from SUGCON EU have been removed from the presentation details of the SUGCON ANZ Sponsors page. I have kept the lists in the data folder for future use in other years.
While in there, I also removed the 'Blastic' reference in the Video Recording sponsors list, as that was a copy from EU and not accurate for ANZ.
=> ANZ - Removed unnecessary sponsor categories

.github/workflows/CI-CD_MVP.yml, .github/workflows/CI-CD_SUGCON_ANZ.yml, .github/workflows/CI-CD_SUGCON_EU.yml, .github/workflows/CI-CD_XM_Cloud.yml, .github/workflows/build_NextJs.yml, .github/workflows/deploy_azureWebapp.yml, .github/workflows/deploy_xmCloud.yml
Tidied up a series of things with the GitHub Actions workflow
- Added missing Path dependencies, to ensure changes to template workflows cause builds
- Fixed a few incorrect labels
- Rearranged MVP paths to match path order from other workflows
- Updated CI-CD Workflow naming to match yml files for consistency.
=> Added missing GitHub Action path dependencies

src/Project/MvpSite/rendering/Extensions/ApplicationBuilderExtensions.cs, src/Project/MvpSite/rendering/Middleware/EnsureAcceptLanguageHeaderMiddleware.cs, src/Project/MvpSite/rendering/Startup.cs, src/Project/MvpSite/rendering/appsettings.json
This is a fix for a bug in the ASP.NET Rendering SDK, where a 404 is thrown if the Accept-Language header isn't included in the main request to load the page.
Tracked internally as `Bug 555373`
closes #163
=> Accept language header error

.github/workflows/CI-CD_MVP.yml, .github/workflows/CI-CD_SUGCON_ANZ.yml, .github/workflows/CI-CD_SUGCON_EU.yml, .github/workflows/CI-CD_SUGCON_Events.yml, .github/workflows/CI-CD_XM_Cloud.yml
PRs from Forks are building successfully, but are failing deploys due to a lack of access to Secrets. This PR disabled deployments for any PR's that are submitted from a Fork.
=> Updated GitHub Actions template to not do deploys for PRs

src/Feature/People/rendering/PeopleFinder/MvpFinder.cs
Currently the logic for the matching the search factes on the MVP Listing Page is incorrect, it currently checks whether any of an MVP's awards match the facets individually.
This causes an issue when selecting both year & type, e.g. if you select 2023 and Technology and MVP who received 2022 Technology and 2023 Ambassador would be returned as they have an award that matches 2023 and an awards that matches Technology..... just not an award that matches both.
This changes the logic to iterate an MVP's awards an ensure that both facets in a single award when multiple are selected.
Closes #232
=> Fixed issue with logic for facets on MVP Listing page

src/Feature/People/rendering/PeopleFinder/MvpFinder.cs
Currently it's not possible to search for the term "Firstname Lastname" on the MVP Directory as it matches the full string against both the firstname and lastname fields.
This PR changes the logic to combine the Firstname & Lastname fields and compare them to the full string entered. We also strip whitespace out of the string before comparison to help with accidental double spaces causing non-matching.
Closes #231
=> Fixed issue with fullname search on MVP listing page

.github/workflows/CI-CD_SUGCON_ANZ.yml, .github/workflows/CI-CD_SUGCON_EU.yml
This change should have been made as part of [e869a17] . That changed the Vercel deploys to no longer generate as part of the build step, and to only do a build. This means we no longer need the separate builds for Prod vs Staging build.
=> Simplification of the SUGCON ANZ & EU Deployment definitions

README.md, init.ps1, src/Project/MvpSite/rendering/appsettings.Development.json
This PR automates the ability to configure this repository to run 'Edge Development mode with No Docker'. It adds a new param to `init.ps1` which will configure the heads, they can the be manually run directly on the host machine.
The README has been updated to include steps required.
Closes #178
=> Automate 'Edge Development mode with No Docker'

New-EdgeToken.ps1
The `NewEdgeToken.ps1` script currently assumes you've ran the repo already and initialised the CLI. This change forces initialisation of the CLI so that it can be run directly without having to run the repo first.
=> Update NewEdgeToken script to initialize cli settings

New-EdgeToken.ps1
The `New-EdgeToken.ps1` script was opening the GraphQL browser IDE with an extra forward slash (/) causing the URL to fail. `edgURL` from the `Response` object contains a trailing forward slash so I removed the one in our code. 
Fix URL for automatically opening the browser based GraphQL IDE
Tested locally with `1C6WJAKXzE6MR09hYzdzSH` Environment Id.
=> Remove extra forward slash in URL

src/Project/Sugcon/SugconAnzSxa/src/assets/app.scss
Adjusted app sass styles used in the header to address some issues identified when testing the rebranding on SUGCON ANZ site.  Specifically:
1. Remove explicit usage of the #666 background-color in .header .richtext allowing it to fall back to the class/bg colour used in the container (background-dark-grey / #707070)
2. Reduce the logo image width in a media query in css to avoid it clashing with on mobile screens below XS breakpoint
3. Vertically align the navbar options
Tested locally in Full local development mode with the SUGCON ANZ site running locally in connected mode.  The style changes should be contained to the SUGCON ANZ site.
=> Header and nav style tweaks for SUGCON ANZ

src/Project/Sugcon/SugconAnzSxa/src/Layout.tsx, src/Project/Sugcon/SugconEuSxa/src/Layout.tsx, src/Project/Sugcon/SugconIndiaSxa/src/Layout.tsx, src/Project/Sugcon/SugconNaSxa/src/Layout.tsx
Fixes #288 by lowercasing the open graph tags for Image and Type in the SUGCON sites. This will hopefully correct the Teams issues of loading images for SUGCON pages.
Tested on Vercel preview site and in Teams.
=> Fixing casing of og:Image and og:Type on SUGCON sites to lowercase

docker-compose.override.yml
This fixes #316 
Add SITECORE_GraphQL_CORS to the docker-compose-override.yml environment variables for the cm container.  This will allow Pages to connect to the local cm container.
I tested by updating the .env file to 
1. leave out the SITECORE_GraphQL_CORS
2. set the SITECORE_GraphQL_CORS to an empty value
3. set the SITECORE_GraphQL_CORS to an incorrect value
4. set the SITECORE_GraphQL_CORS to the correct value
5. 
- [] My change is a documentation change and there are NO other updates required.
=> Add SITECORE_GraphQL_CORS environment variable

src/Project/Sugcon2024/Sugcon/src/components/Hero/Hero.stories.ts
=> Fixing arguments for JSS Hero Component

.github/workflows/CI-CD_XM_Cloud.yml
Updated the CI-CD definition for XMC to also trigger on files changes for the SUGCON heads, as those changes need to be reflected in the Editing Hosts that XMC deploys
=> Changed XMC build to be triggered for Rendering Host changes

src/Feature/Selections/rendering/Models/Any/MyDataEditModel.cs, src/Feature/Selections/rendering/ViewComponents/Any/MyDataEditViewComponent.cs, src/Feature/Selections/rendering/Views/Shared/Components/AnyMyDataEdit/Default.cshtml
This displays your image when editing your profile data
Users can't validate their image currently unless the Directory updates which is on a 1h cache. With this users can make their choice of Image Type more reliably.
Manual UI Test
Local Machine
=> Display Image at My Data

.env.template
All docker base images are now running against LTSC2022.
=> Bumped images version, so all docker images default to LTSC2022

src/Project/Sugcon2024/Sugcon/.eslintrc, src/Project/Sugcon2024/Sugcon/package-lock.json, src/Project/Sugcon2024/Sugcon/package.json, src/Project/Sugcon2024/Sugcon/src/components/Events/Agenda.tsx, src/Project/Sugcon2024/items/Modules/Sugcon2024/Events.yml, src/Project/Sugcon2024/items/Renderings/Sugcon2024/Events.yml, src/Project/Sugcon2024/items/Renderings/Sugcon2024/Events/Agenda.yml, src/Project/Sugcon2024/items/SiteEU/EU/Presentation/Page Designs.yml, src/Project/Sugcon2024/items/SiteShared/Shared/Data/Events.yml, src/Project/Sugcon2024/items/SiteShared/Shared/Presentation/Available Renderings/Events.yml, src/Project/Sugcon2024/items/Templates/Sugcon2024/Events.yml, src/Project/Sugcon2024/items/Templates/Sugcon2024/Events/Agenda.yml, src/Project/Sugcon2024/items/Templates/Sugcon2024/Events/Agenda/Content.yml, src/Project/Sugcon2024/items/Templates/Sugcon2024/Events/Agenda/Content/SessionizeUrl.yml, src/Project/Sugcon2024/items/Templates/Sugcon2024/Events/Rendering Parameters.yml, src/Project/Sugcon2024/items/Templates/Sugcon2024/Events/Rendering Parameters/Agenda.yml, src/Project/Sugcon2024/items/Templates/Sugcon2024/Events/Rendering Parameters/Agenda/__Standard Values.yml
The Agenda component is added with PR, it is functional, not ready. It needs styling. 
Also there is a FE-specific comment for the FE Devs in the team, it's about the hook.
I used the useSWR hook for fetching the data, because it is highly recommend to use that rather than the useEffect hook. 
The old approach works with getStaticProps, but the problem with that is, that the data are fetched on build and especially for the agenda we need to have a recent version in place, because the agenda needs to be update in Sessionize during the event. 
Let's discuss please the pros and cons of this, this is just my suggestion.
Tested it locally, works in my FE app and in Pages connected to my local CM.
Added the component and related items.
=> added Agenda component and related items

src/Project/Sugcon2024/Sugcon/src/components/Basic Components/Hero.tsx, src/Project/Sugcon2024/Sugcon/src/stories/components/Basic Components/HomepageHero.stories.ts
Updating the styles to ensure that the hero image fills all of the space and doesn't leave any gaps.
We found some gaps in Storybook at certain screen sizes and needed to touch up the styles.
Locally with storybook at all screen sizes
=> Update styles to fix unwanted space at certain screen sizes

src/Project/Sugcon2024/Sugcon/src/components/Basic Components/Hero.tsx
Removing the image from the letter hero on mobile to match the designs from UX.
When we get into mobile mode we should not show the background image
Locally in Storybook
=> Removing the image from the letter hero on mobile

src/Project/Sugcon2024/Sugcon/src/components/Events/Sessions.tsx, src/Project/Sugcon2024/items/Renderings/Sugcon2024/Events/Sessions.yml, src/Project/Sugcon2024/items/SiteEU/EU/Presentation/Available Renderings/Events.yml, src/Project/Sugcon2024/items/Templates/Sugcon2024/Events/Rendering Parameters/Sessions.yml, src/Project/Sugcon2024/items/Templates/Sugcon2024/Events/Rendering Parameters/Sessions/__Standard Values.yml, src/Project/Sugcon2024/items/Templates/Sugcon2024/Events/Sessions.yml, src/Project/Sugcon2024/items/Templates/Sugcon2024/Events/Sessions/Content.yml, src/Project/Sugcon2024/items/Templates/Sugcon2024/Events/Sessions/Content/SessionizeUrl.yml
Created the Sessions Component and related content items for the SUGCON 2024 EU build
=> SUGCON 2024 EU - Created Sessions Rendering and related Content Items

src/Project/Sugcon2024/Sugcon/src/components/Basic Components/Hero.tsx, src/Project/Sugcon2024/Sugcon/src/lib/utils/sitecoreUtils.ts, src/Project/Sugcon2024/Sugcon/src/stories/components/Basic Components/HomepageHero.stories.tsx, src/Project/Sugcon2024/Sugcon/src/stories/components/Basic Components/JustificationLetterHero.stories.tsx
Updating the field types to use Sitecore fields to be compatible with Experience Editor and Pages
The component wasn't able to be updated inline within Experience Editor or Pages
Locally in Sitecore and Storybook
=> Updates for Hero to support editor editing and Storybook fixes

src/Project/Sugcon/SugconAnzSxa/package.json, src/Project/Sugcon/SugconEuSxa/package.json, src/Project/Sugcon/SugconIndiaSxa/package.json, src/Project/Sugcon/SugconNaSxa/package.json, src/Project/Sugcon2024/Sugcon/package.json
Vercel have removed support for Node12, which has broken our builds. A better solution is to remove the engine definition from our `package.json`, allowing the engine to be defined within the Vercel dashboard itself. This PR makes that change.
Closes #408
=> Removed Engine Node from SUGCON package.json files

.env.template, docker-compose.override.yml, up.ps1
Updated the repo to leverage the new XMC specific Docker Tools image, as per this note in the ChangeLog: https://developers.sitecore.com/changelog/xm-cloud/new-xm-cloud-docker-tools-image
Closes #411
=> Updated to new XMC Docker Tools image

src/Project/Sugcon2024/Sugcon/next.config.js
Remove `assetPrefix` from `next.config.js`
I have removed the `assetPrefix` configuration from `next.config.js` because it is not required for our project's current hosting setup. The `assetPrefix` setting is utilized when Next.js applications need to serve their static assets from an offsite CDN. However, our project's assets are served directly from Vercel's CDN, which optimizes asset delivery by default. [Next.js documentation specifies](https://nextjs.org/docs/api-reference/next.config.js/asset-prefix) that deploying to Vercel automatically configures a global CDN for your project, negating the need for a manual `assetPrefix` setup.
This was tested locally, with `assetPrefix` in place I can see the assets are prefixed with `http://localhost:300`. Without the `assetPrefix` in place, …
=> Fix asset pointer error

src/Project/Sugcon2024/Sugcon/package.json, src/Project/Sugcon2024/Sugcon/src/pages/_app.tsx
Added the snippet for enabling Vercel's Speed Insights functionality for the SUGCON EU site.
https://vercel.com/sitecoretechnicalmarketing/sugcon24/speed-insights
This will allow us to track the overall performance of the site according to the Core Web Vitals standard.
I've also included an environment variable for toggling this setting. @lovesitecore you can enable this feature by adding `NEXT_PUBLIC_ENABLE_SPEED_INSIGHTS=true` to the project's environment variables.
 
I've added this snippet locally and run the site.
- [] My change is a documentation change and there are NO other updates required.
=> SUGCON24 EU: Vercel Speed Insights

src/Project/Sugcon2024/Sugcon/src/Theme.ts, src/Project/Sugcon2024/Sugcon/src/components/Basic Components/Person.tsx, src/Project/Sugcon2024/Sugcon/src/components/List Components/PeopleGrid.tsx, src/Project/Sugcon2024/Sugcon/src/components/List Components/SpeakersGrid.tsx
Fixing layout issues across breakpoints for the SpeakersGrid and Person components.
https://sugcon24eu.vercel.app/Speakers
Local dev and storybook
=> Fix layout issues for speakersgrid and person components.

src/Project/Sugcon2024/Sugcon/src/components/Navigation.tsx
When clicking a link in the mobile menu, the menu doesn't close automatically because Next.js only re-renders components that have changed. To close the menu on navigation, we pass the onToggle function to the link components and call it onClick, triggering a state change and re-render of the menu.
Local dev and storybook.
=> Pass onToggle to Navigation children and call on link click so menu closes on route changes.

src/Project/Sugcon2024/Sugcon/package.json, src/Project/Sugcon2024/Sugcon/src/components/Events/Agenda.tsx
On the agenda page, the popup for the session details was not opening.  The html from sessionize includes the javascript function to open the modal.  The dangerouslySetHtml attribute does not render script tags. I used this node module https://www.npmjs.com/package/dangerously-set-html-content.
=> Call dangerously set to allow script tags

src/Project/Sugcon2024/Sugcon/src/components/Basic Components/Person.tsx, src/Project/Sugcon2024/Sugcon/src/components/Basic Components/Venue.tsx
The People Grid Component is used in 2 different occasions: The Featured Speakers and the organizers. In both cases, the Images of each person should be displayed as a square with rounded edges. When using images that are not cropped to square the layout looks odd. So the css should handle the cropping to preserve the layout. 
Added the object-fit: cover attribute along with an additional alt attribute to improve Lighthouse Scores and Accessibility. 
Test locally.
=> Fix images for PeopleGrid Component

src/Project/Sugcon2024/Sugcon/src/components/Basic Components/Hero.tsx
The Event Variant of Hero Banner had a padding at the top. So I exchanged the markup with the one that has been fixed for the main variant and change background to black and font color  to white.
see above
tested locally
=> Fixed padding top and applied same component structure as Other Hero Variant

.github/workflows/CI-CD_XM_Cloud.yml, .github/workflows/deploy_xmCloud.yml, .github/workflows/promote_xmCloud.yml
Currently the CI/CD Pipeline for XMC runs a build for both Staging and Prod envs, The aim has always been to promote the successful build from Staging to Prod, instead of building again as that slows down the deployment process.
This was blocked previously due to a missing feature in the CLI, that feature has been added and this change now updates the process accordingly.
Resolves #230
=> Changed XMC DevOps process to use Promote

src/Project/Sugcon2024/Sugcon/src/components/List Components/Accordion.tsx, src/Project/Sugcon2024/Sugcon/src/components/List Components/PeopleGrid.tsx, src/Project/Sugcon2024/Sugcon/src/components/List Components/SpeakersGrid.tsx
If the Data Source of `Accordion` rendering is empty, the rendering host will return a 500 Internal Server Error. The same issue exists with `PeopleGrid` and `SpeakersGrid` renderings as well.
Local
=> SUGCON24 EU: Fix Null Reference Exception bug in ListComponents

Packages.props, src/Feature/Selections/rendering/Attributes/HttpsUrlAttribute.cs, src/Feature/Selections/rendering/Models/Admin/ApplicationReviewSettingsModel.cs, src/Feature/Selections/rendering/Models/Admin/ApplicationsOverviewModel.cs, src/Feature/Selections/rendering/Models/Admin/AwardModel.cs, src/Feature/Selections/rendering/Models/Admin/ScoreCardDetailModel.cs, src/Feature/Selections/rendering/Models/Admin/ScoreCardsModel.cs, src/Feature/Selections/rendering/Models/Admin/UserEditModel.cs, src/Feature/Selections/rendering/Models/Any/MyDataEditModel.cs, src/Feature/Selections/rendering/Models/Any/MyProfilesFormModel.cs, src/Feature/Selections/rendering/Models/Apply/ApplicationFormModel.cs, src/Feature/Selections/rendering/Models/BaseModel.cs, src/Feature/Selections/rendering/Models/ListModel.cs, src/Feature/Selections/rendering/ViewComponents/Admin/ApplicationCommentViewComponent.cs, src/Feature/Selections/rendering/ViewComponents/Admin/ApplicationOverviewViewComponent.cs, src/Feature/Selections/rendering/ViewComponents/Admin/ApplicationReviewSettingsViewComponent.cs, src/Feature/Selections/rendering/ViewComponents/Admin/AwardViewComponent.cs, src/Feature/Selections/rendering/ViewComponents/Admin/RegionsOverviewViewComponent.cs, src/Feature/Selections/rendering/ViewComponents/Admin/ScoreCardDetailViewComponent.cs, src/Feature/Selections/rendering/ViewComponents/Admin/ScoreCardsViewComponent.cs, src/Feature/Selections/rendering/ViewComponents/Admin/UserEditViewComponent.cs, src/Feature/Selections/rendering/ViewComponents/Admin/UsersOverviewViewComponent.cs, src/Feature/Selections/rendering/ViewComponents/Any/MyDataEditViewComponent.cs, src/Feature/Selections/rendering/ViewComponents/Any/MyProfilesFormViewComponent.cs, src/Feature/Selections/rendering/ViewComponents/Apply/ApplicationFormViewComponent.cs
+ Added validation for ProfileLink Uri so the API error wouldn't show
+ Nuget package updates Selections Feature
+ Syntax adjustment new and collection initializers
The API was altered to only accept https URI as ProfileLinks
Manual UI Test
Local machine
=> Adds Validation for ProfileLink Uri

README.md, authoring/platform/Packages.props, headapps/MvpSite/Directory.Packages.props, headapps/MvpSite/MvpSite.Rendering/AppSettings/MvpSiteSettings.cs, headapps/MvpSite/MvpSite.Rendering/Startup.cs, headapps/MvpSite/MvpSite.Rendering/appsettings.json
This change updates the MVP site to connect via Context ID
* Updated to latest SDK Version
* Change startup to leverage ContextID connection
* Updated README to reflect this change
* Tidied up package definitions.
Closes #486
=> Updated MVP Site to connect using ContextID

.github/workflows/CI-CD_MVP.yml, .github/workflows/CI-CD_SUGCON_24.yml, .github/workflows/CI-CD_SUGCON_24_STORYBOOK.yml, .github/workflows/CI-CD_XM_Cloud.yml
Remove the forced check on account status in the CI-CD pipelines
This forced check is no longer required, it is now handled by the "Approval for running fork pull request workflows from contributors" setting on the repo.
- [] New feature (non-breaking change which adds functionality)
=> Removed push account check, handled by settings instead

headapps/MvpSite/MvpSite.Rendering/ViewComponents/Apply/ApplicationFormViewComponent.cs
Fixes other parts of Application form to submit full application instead of partial with empty values
API Client can't determine whether null is desirable to pass or to ignore so must pass full application atm to prevent data loss due to values being reset as null values are passed down to the API
Manual Testing
Local Docker Setup
=> Fixed additional partial application updates

authoring/items/Mvp/Project.MvpSite/items/content/MvpSite/Shared Content/Directory.yml, authoring/items/Mvp/Project.MvpSite/items/content/MvpSite/Shared Content/Directory/Mentor.yml, headapps/MvpSite/Directory.Packages.props, headapps/MvpSite/MvpSite.Rendering/Extensions/BooleanExtensions.cs, headapps/MvpSite/MvpSite.Rendering/ViewComponents/DirectoryViewComponent.cs
Adds the Mentor facet to the Directory
Allows filtering directory results by Mentorship and Open To Mentees
Manual UI Testing
Local Docker
=> Mentor Facet

headapps/MvpSite/MvpSite.Rendering/Views/Shared/_Layout.cshtml
This PR removes the version indicator from the main.min.css reference in the head which prevents loading latest version
Local
=> Remove version from css reference

authoring/items/Sugcon2024/Sugcon/Sugcon/SiteANZ/ANZ/Home.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/SiteANZ/ANZ/Home/Agenda.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/SiteANZ/ANZ/Home/Agenda/Data/Agenda EU.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/SiteANZ/ANZ/Home/On-Demand.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/SiteANZ/ANZ/Home/Organizers.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/SiteANZ/ANZ/Home/Sessions.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/SiteANZ/ANZ/Home/Speakers.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/SiteANZ/ANZ/Home/Speakers/Data/Speakers.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/SiteANZ/ANZ/Home/Sponsors.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/SiteANZ/ANZ/Home/Venue.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/SiteANZ/ANZ/Home/Workshops.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/SiteANZ/ANZ/Presentation/Page Designs.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/SiteANZ/ANZ/Presentation/Page Designs/ANZ Generic Page.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/SiteANZ/ANZ/Presentation/Page Designs/ANZ HomePage.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/SiteANZ/ANZ/Presentation/Partial Designs/ANZ Header.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/SiteANZ/ANZ/Presentation/Placeholder Settings/Partial Design/ANZ Header.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/Templates/Sugcon2024/Page Templates/ANZ Generic Page.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/Templates/Sugcon2024/Page Templates/ANZ Generic Page/Content.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/Templates/Sugcon2024/Page Templates/ANZ Generic Page/Content/Content.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/Templates/Sugcon2024/Page Templates/ANZ Generic Page/Content/Title.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/Templates/Sugcon2024/Page Templates/ANZ Generic Page/__Standard Values.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/Templates/Sugcon2024/Page Templates/ANZ Home Page.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/Templates/Sugcon2024/Page Templates/ANZ Home Page/Content.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/Templates/Sugcon2024/Page Templates/ANZ Home Page/Content/Content.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/Templates/Sugcon2024/Page Templates/ANZ Home Page/Content/Title.yml, authoring/items/Sugcon2024/Sugcon/Sugcon/Templates/Sugcon2024/Page Templates/ANZ Home Page/__Standard Values.yml
Attempt to fix menu caching issue, by changing the ANZ site to use its own dedicated header partial, and site specific page designs.
=> Changed ANZ to use dedicated page templates

headapps/MvpSite/MvpSite.Rendering/Views/Shared/Components/Directory/Default.cshtml, headapps/MvpSite/MvpSite.Rendering/wwwroot/js/mvp-site.js
Fixes the issue where the Directory search input field retains its value when using browser back navigation, even though the URL query parameter (`q`) is removed.
- User searches for "Gaurav" in Directory → results are displayed
- User clicks browser back button → URL query parameter `q` is removed 
- Search input field still shows "Gaurav" text (inconsistent state)
Added `directorySearchClearHandler()` function that:
- Monitors URL query parameters and clears input when `q` parameter is missing
- Handles multiple browser navigation scenarios:
- `popstate` events (back/forward navigation)
- `pageshow` events (page restoration from cache)
- `visibilitychange` events (tab switching)
- Includes fallback mechanisms:
- MutationObserver for DOM changes
- Property descriptor override for input …
=> Fix Directory search input not clearing on browser back navigation - Issues/431

headapps/MvpSite/MvpSite.Rendering/ViewComponents/Any/MyDataEditViewComponent.cs, headapps/MvpSite/MvpSite.Rendering/Views/Shared/Components/AnyMyDataEdit/Default.cshtml
- Hide Twitter option from profile image dropdown
- Convert existing Twitter selections to Anonymous automatically  
- Apply Twitter-to-Anonymous conversion on load and save operations
- Fix errors for users who previously selected Twitter as image
- Manual UI Testing in localhost running app
https://github.com/user-attachments/assets/5d82983e-fe91-4465-b080-f9feb07a83f5
Closes #349
=> fix #349: Remove Twitter as profile image source option due to API restrictions

headapps/MvpSite/MvpSite.Rendering/Views/Shared/Components/Profile/Default.cshtml
This change updates the Razor view to ensure that the timeline section is only rendered when there are timeline events available. Previously, the timeline container was always rendered, even if no events were present, which could result in empty or misleading UI sections.
This improves the user experience by displaying relevant content only when available and avoids rendering unnecessary HTML markup.
- Manually tested the profile view with and without timeline events.
**Verified that:**
- The timeline section appears only when Model.GetTimelineEvents() returns items.
- The section is hidden when the timeline is empty or null.
- Tested in local development environment using Visual Studio 2022.
- Confirmed that no layout or styling issues occur due to conditional rendering.
=> Fix for Remove Timeline if no item is listed #545

headapps/Sugcon2024/package-lock.json, headapps/Sugcon2024/package.json, headapps/Sugcon2024/src/Layout.tsx
Added GA Tracking for the SUGCON Sites, powered by env var.
=> Added GA Tracking for SUGCON Sites

headapps/MvpSite/MvpSite.Rendering/Program.cs
We need to disable the X-FRAME sameorigin policy when the app is deployed in editing mode, as Pages can't render any pages that contain Form tags currently.
Closes #550
=> Disable X-Frame check when in editing mode
